lab:
  rabbit:
    queue: lab.events.queue

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/lab
    username: lab
    password: lab
